name: vjtiAssistant
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_svg: ^0.20.0-nullsafety.3
  bottom_navy_bar: ^5.5.0
  google_fonts: ^1.1.2
  firebase_core:
  firebase_messaging:
  firebase_auth: ^0.16.0
  firebase_storage: ^3.1.6
  firebase_database: ^3.1.6
  cloud_firestore: ^0.13.6
  fluttertoast: ^7.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    # - assets/images/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
    - family: NotoSansJP
      fonts:
        - asset: fonts/NotoSansJP-Regular.otf
        - asset: fonts/NotoSansJP-Bold.otf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
  uses-material-design: true
